chore: github actions deploy to openshift

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,7 +10,7 @@ on:
       - 'stable'
 
 jobs:
-  integration-tests:
+  integration-tests-local:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -41,9 +41,148 @@ jobs:
         run: |
           docker run --name iqe --network host \
             -e IQE_TESTS_LOCAL_CONF_PATH=/iqe_settings ${{ secrets.IQE_TESTS_IMAGE }} \
-            iqe tests plugin vulnerability -k 'vmaas' --html=report.html --self-contained-html
+            iqe tests plugin vulnerability -k 'vmaas' --long-running --html=report.html --self-contained-html
       - run: docker-compose logs > logs
         if: always()
+      - run: docker cp iqe:/iqe_venv/report.html .
+        if: always()
+      - name: Publish test results
+        uses: actions/upload-artifact@v1
+        if: always()
+        with:
+          name: test-report-local
+          path: report.html
+      - name: Publish logs
+        uses: actions/upload-artifact@v1
+        if: always()
+        with:
+          name: docker-compose-logs
+          path: logs
+
+  integration-tests-openshift:
+    runs-on: ubuntu-latest
+    env:
+      E2E_DEPLOY_PATH: "{{ $GITHUB_WORKSPACE }}/e2e-deploy"
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Check out e2e-deploy
+        uses: actions/checkout@master
+        with:
+          repository: RedHatInsights/e2e-deploy
+          token: "${{ secrets.VMAAS_BOT }}"
+          path: e2e-deploy
+      - name: Cancel previous builds
+        uses: rokroskar/workflow-run-cleanup-action@master
+        env:
+          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+      - name: Set up Python
+        uses: actions/setup-python@v1
+        with:
+          python-version: 3.7
+      - name: Install e2e-deploy's dependencies
+        run: |
+          pip install -U pip
+          pip install -r "${{ E2E_DEPLOY_PATH }}/requirements.txt"
+      - name: Docker Login
+        uses: Azure/docker-login@v1
+        with:
+          username: ${{ secrets.REGISTRY_USERNAME }}
+          password: ${{ secrets.REGISTRY_PASSWORD }}
+          login-server: quay.io
+      - name: OpenShift Login
+        uses: redhat-developer/openshift-actions@v1.1
+        with:
+          version: 'latest'
+          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
+          parameters: '{"apitoken": "${{ secrets.OPENSHIFT_TOKEN }}", "acceptUntrustedCerts": "true"}'
+          useLocalOc: true
+          cmd: |          
+            'login'
+      - name: Build VMaaS
+        run: |
+          cd ${{ E2E_DEPLOY_PATH }}
+          cat <<EOF > env/builder-env.yml
+          vmaas/vmaas-reposcan:
+            parameters:
+              SOURCE_REPOSITORY_REF: "${{ github.ref }}"
+              SOURCE_REPOSITORY_URL: "https://github.com/${{ github.repository }}"
+          vmaas/vmaas-webapp:
+            parameters:
+              SOURCE_REPOSITORY_REF: "${{ github.ref }}"
+              SOURCE_REPOSITORY_URL: "https://github.com/${{ github.repository }}"
+              DOCKERFILE_PATH: webapp/Dockerfile-qe
+          vmaas/vmaas-websocket:
+            parameters:
+              SOURCE_REPOSITORY_REF: "${{ github.ref }}"
+              SOURCE_REPOSITORY_URL: "https://github.com/${{ github.repository }}"
+          vmaas/vmaas-database:
+            parameters:
+              SOURCE_REPOSITORY_REF: "${{ github.ref }}"
+              SOURCE_REPOSITORY_URL: "https://github.com/${{ github.repository }}"
+          EOF
+          # echo "vmaas/vmaas-reposcan:" > env/builder-env.yml
+          # echo "  parameters:" >> env/builder-env.yml
+          # echo "    SOURCE_REPOSITORY_REF: ${{ github.ref }}" >> env/builder-env.yml
+          # echo "    SOURCE_REPOSITORY_URL: ${scmVars.GIT_URL}" >> env/builder-env.yml
+          # echo "vmaas/vmaas-webapp:" >> env/builder-env.yml
+          # echo "  parameters:" >> env/builder-env.yml
+          # echo "    SOURCE_REPOSITORY_REF: ${{ github.ref }}" >> env/builder-env.yml
+          # echo "    SOURCE_REPOSITORY_URL: ${scmVars.GIT_URL}" >> env/builder-env.yml
+          # echo "    DOCKERFILE_PATH: webapp/Dockerfile-qe" >> env/builder-env.yml
+          # echo "vmaas/vmaas-websocket:" >> env/builder-env.yml
+          # echo "  parameters:" >> env/builder-env.yml
+          # echo "    SOURCE_REPOSITORY_REF: ${{ github.ref }}" >> env/builder-env.yml
+          # echo "    SOURCE_REPOSITORY_URL: ${scmVars.GIT_URL}" >> env/builder-env.yml
+          # echo "vmaas/vmaas-database:" >> env/builder-env.yml
+          # echo "  parameters:" >> env/builder-env.yml
+          # echo "    SOURCE_REPOSITORY_REF: ${{ github.ref }}" >> env/builder-env.yml
+          # echo "    SOURCE_REPOSITORY_URL: ${scmVars.GIT_URL}" >> env/builder-env.yml
+
+          ocdeployer deploy -f --sets vmaas \
+            --template-dir buildfactory \
+            -e builder-env vmaas-qe --secrets-src-project secrets
+      - name: Deploy VMaaS
+        run: |
+          cd ${{ E2E_DEPLOY_PATH }}
+          ocdeployer deploy -f --sets vmaas \
+           -e vmaas-qe vmaas-qe --secrets-src-project secrets
+      - name: Sync VMaaS repolist
+        run: ./scripts/setup_db.sh conf/repolist.json \
+         ${{ secrets.OPENSHIFT_REPOSCAN_URL }} \
+         ${{ secrets.OPENSHIFT_WEBAPP_URL }} \
+         ${{ secrets.VMAAS_BOT }}
+      - name: Run VMaaS integration tests
+        run: |
+          cat <<EOF > settings.local.yaml
+          default:
+            VULNERABILITY:
+              vmaas:
+                github:
+                  token: "${{ secrets.GITHUB_TOKEN }}"
+                hostname: "${{ secrets.OPENSHIFT_WEBAPP_URL }}"
+                auth_token: "${{ secrets.VMAAS_BOT }}"
+          EOF
+          docker run --name iqe --network host \
+            -v settings.local.yaml:/iqe_settings \
+            -e IQE_TESTS_LOCAL_CONF_PATH=/iqe_settings ${{ secrets.IQE_TESTS_IMAGE }} \
+            iqe tests plugin vulnerability -k 'vmaas' --html=report.html --self-contained-html
+      - name: Get OpenShift logs
+        if: always()
+        run: |
+          oc project vmaas-qe
+          mkdir -p applogs/
+          PODS=$(oc get pods -o jsonpath='{range .items[*]}{.metadata.name}{"\\n"}')
+          for pod in $PODS; do
+              CONTAINERS=$(oc get pod $pod -o jsonpath='{range .spec.containers[*]}{.name}{"\\n"}' || echo "")
+              if [ -z "$CONTAINERS" ]; then
+                  echo "get logs: pod $pod not found"
+              fi;
+              for container in $CONTAINERS; do
+                  oc logs $pod -c $container > applogs/${pod}_${container}.log || echo "get logs: ${pod}_${container} failed."
+                  echo "Saved logs for $pod container $container"
+              done
+          done
       - run: docker cp iqe:/iqe_venv/report.html .
         if: always()
       - name: Publish test results
@@ -56,5 +195,6 @@ jobs:
         uses: actions/upload-artifact@v1
         if: always()
         with:
-          name: docker-compose-logs
-          path: logs
+          name: openshift-logs
+          path: applogs
+
